version: '3.8'

services:
  myhealthsync360:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myhealthsync360-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "scripts/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - myhealthsync360-network

networks:
  myhealthsync360-network:
    driver: bridge

# For production with external database (optional)
# Uncomment if you need a local database for development
# 
# volumes:
#   postgres_data:
#
# services:
#   db:
#     image: postgres:15-alpine
#     container_name: myhealthsync360-db
#     environment:
#       POSTGRES_DB: myhealthsync360
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-defaultpassword}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     networks:
#       - myhealthsync360-network
#     restart: unless-stopped 